version: '3.3'

services:

  db:
    image: postgres:13.0
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 10s

  aimage:
    image: bburich/aimage-api:latest
    volumes:
      - media:/app/media/
      - static:/app/static/
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    restart: always
  
  nginx:
    image: nginx:1.19.0
    ports:
      - 80:80
    env_file:
      - ./.env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/var/html/media/
      - static:/var/html/static/
    depends_on:
      - aimage

volumes:
  db_data:
  media:
  static: