# Generated by Django 4.1.4 on 2022-12-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
