# Generated by Django 4.1.4 on 2023-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_story_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story',
            new_name='generated_story',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
