# Generated by Django 4.1.4 on 2023-01-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_story_story_generated_story_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='admin_like',
            field=models.BooleanField(default=False),
        ),
    ]
