# Generated by Django 4.1.4 on 2023-01-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image_admin_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='admin_like',
            new_name='moderation_like',
        ),
    ]
